version: 2.1

parameters:
  GIT_USER_EMAIL:
    type: string
    default: "youremail@example.com"
  GIT_USER_NAME:
    type: string
    default: "your-username"

executors:
  build-executor:
    docker:
      - image: lineageos4microg/docker-lineage-cicd:latest
    environment:
      GIT_EMAIL: ${GIT_USER_EMAIL}
      GIT_USERNAME: ${GIT_USER_NAME}

commands:
  setup_environment:
    parameters:
      device_name:
        type: string
    steps:
      - run: echo 'export TARGET_DEVICE=${device_name}' >> $BASH_ENV

  configure_git:
    steps:
      - run:
          name: Configure git user
          command: |
            git config --global user.email "${GIT_EMAIL}"
            git config --global user.name "${GIT_USERNAME}"

  install_git_lfs:
    steps:
      - run:
          name: Install git-lfs
          command: |
            git lfs install

jobs:
  initial_setup:
    executor: build-executor
    steps:
      - checkout
      - configure_git
      - install_git_lfs

  setup:
    parameters:
      target_device:
        type: string
        default: "a7y18lte"
    executor: build-executor
    steps:
      - setup_environment:
          device_name: ${target_device}

  build_lineage:
    parameters:
      branch_name:
        type: string
        default: "lineage-18.1"
    executor: build-executor
    steps:
      - run: |
          mkdir -p ~/android/lineage/src
          cd ~/android/lineage/src
          repo init -u https://github.com/LineageOS/android.git -b ${branch_name} --git-lfs
          # ... the rest of your git clone and build commands ...

workflows:
  version: 2
  build-lineage:
    jobs:
      - initial_setup
      - setup:
          requires:
            - initial_setup
      - build_lineage:
          requires:
            - setup
