version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large

jobs:
  build_lineage:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            free -h
            echo 'export TARGET_VENDOR="samsung"' >> $BASH_ENV
            echo 'export TARGET_DEVICE="a7y18lte"' >> $BASH_ENV
            echo 'export TARGET_TYPE="userdebug"' >> $BASH_ENV
            echo 'export TARGET_BRANCH="lineage-18.1"' >> $BASH_ENV
            echo 'export TARGET_ORG="exynos7885-dev"' >> $BASH_ENV
            echo 'export TARGET_CUSTOM_DEVICE_REPOS="exynos7885-common a7y18lte"' >> $BASH_ENV
            echo 'export TARGET_CUSTOM_DEVICE_VENDOR_REPOS="exynos7885-common"' >> $BASH_ENV
            echo 'export TARGET_CUSTOM_KERNEL_REPO="exynos7885"' >> $BASH_ENV
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
      - run:
          name: Setup Git
          command: |
            sudo apt update
            sudo apt install git-lfs python-is-python3 python3
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git lfs install
      - run:
          name: Sync LineageOS sources
          command: |
            python --version
            mkdir -p ~/android/lineage
            cd ~/android/lineage
            python repo init -u https://github.com/LineageOS/android.git -b $TARGET_BRANCH --git-lfs
            python repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: Clone LineageOS Common Samsung repos
          command: |
            cd ~/android/lineage
            git clone https://github.com/LineageOS/android_device_samsung_slsi_sepolicy device/samsung_slsi/sepolicy -b $TARGET_BRANCH
            git clone https://github.com/LineageOS/android_hardware_samsung hardware/samsung -b $TARGET_BRANCH
            git clone https://github.com/LineageOS/android_hardware_samsung_slsi_libbt hardware/samsung_slsi/libbt -b $TARGET_BRANCH
            git clone https://github.com/LineageOS/android_hardware_samsung_slsi_scsc_wifibt_wifi_hal hardware/samsung_slsi/scsc_wifibt/wifi_hal -b $TARGET_BRANCH
            git clone https://github.com/LineageOS/android_hardware_samsung_slsi_scsc_wifibt_wpa_supplicant_lib hardware/samsung_slsi/scsc_wifibt/wpa_supplicant_lib -b $TARGET_BRANCH
      - run:
          name: Clone Exynos7885 repos
          command: |
            cd ~/android/lineage
            for CUSTOM_DEVICE_REPO in ${TARGET_CUSTOM_DEVICE_REPOS[@]}; do git clone https://github.com/${TARGET_ORG}/android_device_${TARGET_VENDOR}_${CUSTOM_DEVICE_REPO} device/${TARGET_VENDOR}/${CUSTOM_DEVICE_REPO} -b $TARGET_BRANCH; done
            git clone https://github.com/${TARGET_ORG}/android_vendor_${TARGET_VENDOR}_${TARGET_CUSTOM_DEVICE_VENDOR_REPOS} vendor/${TARGET_VENDOR}/${TARGET_CUSTOM_DEVICE_VENDOR_REPOS} -b $TARGET_BRANCH
            git clone https://github.com/${TARGET_ORG}/android_kernel_${TARGET_VENDOR}_${TARGET_CUSTOM_KERNEL_REPO} kernel/${TARGET_VENDOR}/${TARGET_CUSTOM_KERNEL_REPO} -b $TARGET_BRANCH
      - run:
          name: Init Device and build LineageOS
          command: |
            cd ~/android/lineage
            source build/envsetup.sh
            lunch lineage_${TARGET_DEVICE}-${TARGET_TYPE}
            m -j$(nproc) bacon

workflows:
  version: 2
  build-lineage:
    jobs:
      - build_lineage
