version: 2.1

executors:
  build-executor:
    docker:
      - image: lineageos4microg/docker-lineage-cicd:latest

jobs:
  build_lineage:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo 'export TARGET_VENDOR="samsung"' >> $BASH_ENV
            echo 'export TARGET_DEVICE="a7y18lte"' >> $BASH_ENV
            echo 'export TARGET_TYPE="userdebug"' >> $BASH_ENV
            echo 'export TARGET_BRANCH="lineage-18.1"' >> $BASH_ENV
            echo 'export TARGET_ORG="exynos7885-dev"' >> $BASH_ENV
            echo 'export TARGET_CUSTOM_DEVICE_REPOS="exynos7885-common a7y18lte"' >> $BASH_ENV
            echo 'export TARGET_CUSTOM_DEVICE_VENDOR_REPOS="exynos7885-common"' >> $BASH_ENV
            echo 'export TARGET_CUSTOM_KERNEL_REPO="exynos7885"' >> $BASH_ENV
            echo 'export TARGET_LINEAGE_COMMON_REPOS=(
                    "device/samsung_slsi_sepolicy:device/samsung_slsi/sepolicy"
                    "hardware/samsung"
                    "hardware/samsung_slsi_libbt:hardware/samsung_slsi/libbt"
                    "hardware/samsung_slsi_scsc_wifibt_wifi_hal:hardware/samsung_slsi/scsc_wifibt/wifi_hal"
                    "hardware/samsung_slsi_scsc_wifibt_wpa_supplicant_lib:hardware/samsung_slsi/scsc_wifibt/wpa_supplicant_lib"
                   )' >> $BASH_ENV
      - run:
          name: Setup Git
          command: |
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git lfs install
      - run:
          name: Sync LineageOS sources
          command: |
            mkdir -p ~/android/lineage
            cd ~/android/lineage
            repo init -u https://github.com/LineageOS/android.git -b $TARGET_BRANCH --git-lfs
            repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: Clone LineageOS Common Samsung repos
          command: |
            cd ~/android/lineage
            # [@Razuuu]: ChatGPT helped me with this crazy thing lmao
            for TARGET_LINEAGE_COMMON_REPO in "${TARGET_LINEAGE_COMMON_REPOS[@]}"; do
             source_path="${TARGET_LINEAGE_COMMON_REPO%%:*}"
             destination_path="${TARGET_LINEAGE_COMMON_REPO#*:}"
             modified_source_path="android_${source_path//\//_}"
             
             git clone https://github.com/LineageOS/${source_path} $destination_path -b $TARGET_BRANCH
            done
      - run:
          name: Clone Exynos7885 repos
          command: |
            cd ~/android/lineage
            for CUSTOM_DEVICE_REPO in ${TARGET_CUSTOM_DEVICE_REPOS[@]}; do git clone https://github.com/${TARGET_ORG}/android_device_${TARGET_VENDOR}_${CUSTOM_DEVICE_REPO} device/${TARGET_VENDOR}/${CUSTOM_DEVICE_REPO} -b $TARGET_BRANCH; done
            git clone https://github.com/${TARGET_ORG}/android_vendor_${TARGET_VENDOR}_${TARGET_CUSTOM_DEVICE_VENDOR_REPOS} vendor/${TARGET_VENDOR}/${TARGET_CUSTOM_DEVICE_VENDOR_REPOS} -b $TARGET_BRANCH
            git clone https://github.com/${TARGET_ORG}/android_kernel_${TARGET_VENDOR}_${TARGET_CUSTOM_KERNEL_REPO} kernel/${TARGET_VENDOR}/${TARGET_CUSTOM_KERNEL_REPO} -b $TARGET_BRANCH
      - run:
          name: Init Device and build LineageOS
          command: |
            cd ~/android/lineage
            source build/envsetup.sh
            lunch lineage_${TARGET_DEVICE}-${TARGET_TYPE}
            m -j$(nproc) bacon

workflows:
  version: 2
  build-lineage:
    jobs:
      - build_lineage
