version: 2.1

executors:
  build-executor:
    docker:
      - image: lineageos4microg/docker-lineage-cicd:latest

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - setup_environment
      - run:
    name: Configure git user
    command: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
      - sync_repositories
      - build_lineageos

commands:
  setup_environment:
    steps:
      - run: echo 'export TARGET_DEVICE=a7y18lte' >> $BASH_ENV

  sync_repositories:
    steps:
      - run: |
          mkdir -p ~/lineage/src
          cd ~/lineage/src
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          git clone https://github.com/exynos7885-dev/android_device_samsung_exynos7885-common.git -b lineage-20.0 device/samsung/exynos7885-common

  build_lineageos:
    steps:
      - run: |
          cd ~/lineage/src
          source build/envsetup.sh
          lunch lineage_a718lte-userdebug m -j$(nproc) bacon

workflows:
  version: 2
  build-lineage:
    jobs:
      - build
